version: "3"
services:

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"

  order-service:
    build:
      context: .
      dockerfile: ./order/Dockerfile
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
    command: gunicorn -b 0.0.0.0:5000 app:app -w 1 --timeout 10
    env_file:
      - env/order_redis.env

  order-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb

  stock-service:
    build:
      context: .
      dockerfile: ./stock/Dockerfile
    image: stock:latest
    command: gunicorn -b 0.0.0.0:5000 app:app -w 1 --timeout 10
    env_file:
      - env/stock_redis.env

  stock-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-service:
    build:
      context: .
      dockerfile: ./payment/Dockerfile
    image: user:latest
    command: gunicorn -b 0.0.0.0:5000 app:app -w 1 --timeout 10
    env_file:
      - env/payment_redis.env

  payment-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb
